---
name: release

"on":
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Write buildtime
        run: date >| .github/RELEASEDATE

      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: .github/RELEASEDATE
          message: "docs: automated release update [skip ci]"
          push: true
          commit: --signoff

...
